/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Volunteer;

import business.Enterprise.FoodBankEnterprise;
import business.UserAccount.CustomerAccount;
import business.VolunteerJob.VolunteerJob;
import business.WorkQueue.ApplyVolunteerRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 梦菲
 */
public class HistoryAndApplyStatusJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CustomerAccount customerAccount;

    /**
     * Creates new form VolunteerApplyStatusJPanel
     */
    public HistoryAndApplyStatusJPanel(JPanel userProcessContainer, CustomerAccount customerAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerAccount = customerAccount;
        populateRequestStatusTable();
        populateHistoryTable(customerAccount);
    }

    private void populateHistoryTable(CustomerAccount customerAccount) {
        DefaultTableModel model = (DefaultTableModel) tblVolunteerHistory.getModel();

        model.setRowCount(0);

        for (Map.Entry<Date, VolunteerJob> entry : customerAccount.getVolunteerJobHistory().entrySet()) {
            Object[] row = new Object[3];
            row[0] = entry.getValue().getJobID();
            row[1] = entry.getValue();
            row[2] = entry.getKey();
            model.addRow(row);
        }
    }

    public void populateRequestStatusTable() {
        DefaultTableModel model = (DefaultTableModel) tblApplyStatus.getModel();

        model.setRowCount(0);
        for (WorkRequest request : customerAccount.getWorkQueue().getWorkRequestList()) {
            if (request instanceof ApplyVolunteerRequest) {
                ApplyVolunteerRequest req = (ApplyVolunteerRequest) request;
                Object[] row = new Object[4];
                row[0] = req.getJob().getJobID();
                row[1] = req.getJob();
                row[2] = req.getJob().getInsitution();
                row[3] = req;

                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblApplyStatus = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVolunteerHistory = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("View Current Apply Status");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        tblApplyStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Job Title", "Institution", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblApplyStatus);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 150));

        jLabel2.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel2.setText("View Your volunteer history");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        tblVolunteerHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Job Title", "End Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVolunteerHistory);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 150));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));

        btnDone.setText("Job Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });
        add(btnDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        int row = tblApplyStatus.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ApplyVolunteerRequest request = (ApplyVolunteerRequest) tblApplyStatus.getValueAt(row, 3);
        VolunteerJob job = (VolunteerJob) tblApplyStatus.getValueAt(row, 1);
        customerAccount.getVolunteerJobHistory().put(new Date(), job);
        customerAccount.getWorkQueue().getWorkRequestList().remove(request);
        populateRequestStatusTable();
        populateHistoryTable(customerAccount);
    }//GEN-LAST:event_btnDoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblApplyStatus;
    private javax.swing.JTable tblVolunteerHistory;
    // End of variables declaration//GEN-END:variables
}
