/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Volunteer;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Organization.VolunteerServiceOrganization;
import business.UserAccount.CustomerAccount;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import userinterface.Enterprise.FindFoodBankJPanel;

/**
 *
 * @author asahoho
 */
public class VolunteerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CustomerAccount customerAccount;


    public VolunteerWorkAreaJPanel(JPanel userProcessContainer, CustomerAccount customerAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerAccount = customerAccount;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFindFoodBank = new javax.swing.JButton();
        btnViewStatusAndHistory = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Volunteer Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        btnFindFoodBank.setText("Find your local food bank for opportunity>>");
        btnFindFoodBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindFoodBankActionPerformed(evt);
            }
        });
        add(btnFindFoodBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        btnViewStatusAndHistory.setText("View your apply status & history>>");
        btnViewStatusAndHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStatusAndHistoryActionPerformed(evt);
            }
        });
        add(btnViewStatusAndHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindFoodBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindFoodBankActionPerformed
            FindFoodBankJPanel findFoodBankJPanel = new FindFoodBankJPanel(userProcessContainer,customerAccount);
            userProcessContainer.add("findFoodBankJPanel", findFoodBankJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFindFoodBankActionPerformed

    private void btnViewStatusAndHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStatusAndHistoryActionPerformed
            HistoryAndApplyStatusJPanel historyAndApplyStatusJPanel = new HistoryAndApplyStatusJPanel(userProcessContainer,customerAccount);
            userProcessContainer.add("historyAndApplyStatusJPanel", historyAndApplyStatusJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewStatusAndHistoryActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFindFoodBank;
    private javax.swing.JButton btnViewStatusAndHistory;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
