/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Volunteer;

import business.WorkQueue.ApplyVolunteerRequest;
import business.Enterprise.FoodBankEnterprise;
import business.Organization.Organization;
import business.UserAccount.*;
import business.VolunteerJob.*;
import business.WorkQueue.*;
import business.Role.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import userinterface.VolunteerServiceRole.AcceptVolunteerJPanel;

/**
 *
 * @author 梦菲
 */
public class VolunteerOpportunityJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CustomerAccount customerAccount;
    private FoodBankEnterprise foodbank;

    public VolunteerOpportunityJPanel(JPanel userProcessContainer, CustomerAccount customerAccount, FoodBankEnterprise foodbank) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerAccount = customerAccount;
        this.foodbank = foodbank;
        txtAreaJobDetails.setEnabled(false);
        tblVolunteerJob.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                VolunteerJob job = (VolunteerJob) tblVolunteerJob.getValueAt(e.getLastIndex(), 2);
                txtAreaJobDetails.setText(job.getDescription());
            }
        });
        populateTable(foodbank);
    }

    private void populateTable(FoodBankEnterprise enterprise) {
        DefaultTableModel model = (DefaultTableModel) tblVolunteerJob.getModel();

        model.setRowCount(0);

        for (VolunteerJob volunteerJob : enterprise.getVolunteerJobs().getVolunteerJobList()) {
            Object[] row = new Object[3];
            row[0] = volunteerJob.getJobID();
            row[1] = volunteerJob.getInsitution();
            row[2] = volunteerJob;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVolunteerJob = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaJobDetails = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnApply = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVolunteerJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Institution", "Volunteer Job Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVolunteerJob);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 160));

        txtAreaJobDetails.setColumns(20);
        txtAreaJobDetails.setRows(5);
        jScrollPane2.setViewportView(txtAreaJobDetails);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 452, 120));

        jLabel1.setText("Job details:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });
        add(btnApply, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, -1, -1));

        jLabel2.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel2.setText("Volunteer Job List");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        int row = tblVolunteerJob.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ApplyVolunteerRequest request = new ApplyVolunteerRequest();
        VolunteerJob job = (VolunteerJob) tblVolunteerJob.getValueAt(row, 2);
        request.setSender(customerAccount);
        request.setJob(job);
        request.setStatus("Apply");
        customerAccount.getWorkQueue().getWorkRequestList().add(request);
        foodbank.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Successfully applied!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnApplyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVolunteerJob;
    private javax.swing.JTextArea txtAreaJobDetails;
    // End of variables declaration//GEN-END:variables
}
