/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Donor;

import business.UserAccount.*;
import business.User.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 梦菲, Lisha
 */
public class DonateHistoryJPanel extends javax.swing.JPanel {

    private CustomerAccount customerAccount;
    private JPanel userProcessContainer;

    /**
     * Creates new form DonateHistoryJPanel
     */

    public DonateHistoryJPanel(JPanel userProcessContainer, CustomerAccount customerAccount) {
        initComponents();
        this.customerAccount = customerAccount;
        this.userProcessContainer = userProcessContainer;
        populateDonateHistoryTable();
    }

    public void populateDonateHistoryTable() {
        DefaultTableModel model = (DefaultTableModel) tableDonateHistory.getModel();
        model.setRowCount(0);

        for (DonateInfo di : customerAccount.getDonateHistory()) {
            Object[] row = new Object[4];
            row[0] = di.getDonateID();
            row[1] = di.getFoodBankName();
            row[2] = di.getAmount();
            row[3] = di.getDate();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDonateHistory = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Your Donate History");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 35, -1, -1));

        tableDonateHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Institution", "Amount", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDonateHistory);
        if (tableDonateHistory.getColumnModel().getColumnCount() > 0) {
            tableDonateHistory.getColumnModel().getColumn(0).setResizable(false);
            tableDonateHistory.getColumnModel().getColumn(1).setResizable(false);
            tableDonateHistory.getColumnModel().getColumn(2).setResizable(false);
            tableDonateHistory.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 250));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDonateHistory;
    // End of variables declaration//GEN-END:variables
}
