/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Donor;

import static business.Enterprise.Enterprise.EnterpriseType.FoodBank;
import business.Enterprise.FoodBankEnterprise;
import business.User.*;
import business.UserAccount.*;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author asahoho
 */
public class DonateJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private CustomerAccount customerAccount;
    private FoodBankEnterprise foodBank;

    /**
     * Creates new form DonateJPanel
     */
    public DonateJPanel(JPanel userProcessContainer, CustomerAccount customerAccount, FoodBankEnterprise foodBank) {
        initComponents();
        this.customerAccount = customerAccount;
        this.userProcessContainer = userProcessContainer;
        this.foodBank = foodBank;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("Amount");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 106, -1, -1));

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 109, 165, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel2.setText("Donate Here Please");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 26, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        DonateInfo di = new DonateInfo();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        double amount;
        try {
            amount = Double.parseDouble(txtAmount.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please fill in valid Amount");
            return;
        }
        if (amount <= 0) {
            JOptionPane.showMessageDialog(null, "Please fill in valid Amount");
            return;
        }
        di.setAmount(amount);
        di.setDate(date);
        di.setFoodBankName(foodBank.getName());
        foodBank.addBalance(amount);
        customerAccount.getDonateHistory().add(di);
        txtAmount.setText("");
        JOptionPane.showMessageDialog(null, "Donate successfully. Thank you for your donate.");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
