/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Donor;

import business.EcoSystem;
import business.User.*;
import business.UserAccount.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import userinterface.Enterprise.FindFoodBankJPanel;

/**
 *
 * @author asahoho
 */
public class DonorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CustomerAccount customerAccount;

    /**
     * Creates new form DonorWorkAreaJPanel
     */
    public DonorWorkAreaJPanel(JPanel userProcessContainer, CustomerAccount customerAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerAccount = customerAccount;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewDonateHistory = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        donateToFoodBank = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Donor Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        viewDonateHistory.setText("View your donate histroy>>");
        viewDonateHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDonateHistoryActionPerformed(evt);
            }
        });
        add(viewDonateHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        donateToFoodBank.setText("Donate to a food bank>>");
        donateToFoodBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateToFoodBankActionPerformed(evt);
            }
        });
        add(donateToFoodBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void donateToFoodBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateToFoodBankActionPerformed
            FindFoodBankJPanel findFoodBankJPanel = new FindFoodBankJPanel(userProcessContainer,customerAccount);
            userProcessContainer.add("findFoodBankJPanel", findFoodBankJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_donateToFoodBankActionPerformed

    private void viewDonateHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDonateHistoryActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ViewDonateHistory", new DonateHistoryJPanel(userProcessContainer, customerAccount));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewDonateHistoryActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton donateToFoodBank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewDonateHistory;
    // End of variables declaration//GEN-END:variables
}
