/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Enterprise;

import business.EcoSystem;
import business.Enterprise.FoodBankEnterprise;
import business.UserAccount.CustomerAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.AdministrativeRole.AdminWorkAreaJPanel;
import userinterface.Customer.CustomerWorkAreaJPanel;
import userinterface.Donee.DoneeGetHelpJPanel;
import userinterface.Donee.DoneeWorkAreaJPanel;
import userinterface.Donor.DonateJPanel;
import userinterface.Donor.DonorWorkAreaJPanel;
import userinterface.Volunteer.VolunteerOpportunityJPanel;
import userinterface.Volunteer.VolunteerWorkAreaJPanel;

/**
 *
 * @author 梦菲
 */
public class FoodBankInfoJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CustomerAccount customerAccount;
    //private final EcoSystem system;
    private FoodBankEnterprise foodbank;

    /**
     * Creates new form FoodBankInfoJPanel
     */
    public FoodBankInfoJPanel(JPanel userProcessContainer, FoodBankEnterprise foodbank, CustomerAccount customerAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerAccount = customerAccount;
        this.foodbank = foodbank;
        //system = EcoSystem.getInstance();
        displayFoodBank();
        defaultView();
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray.length > 0 ? componentArray[componentArray.length - 1] : null;
        Component comp = componentArray.length > 1 ? componentArray[componentArray.length - 2] : null;
        btnUpdate.setVisible(false);
        btnSave.setVisible(false);
        btnDonate.setVisible(false);
        btnVolunteer.setVisible(false);
        btnHelp.setVisible(false);
        if (component instanceof AdminWorkAreaJPanel) {
            btnUpdate.setVisible(true);
            btnSave.setVisible(true);
        } else if (comp instanceof CustomerWorkAreaJPanel) {
            btnDonate.setVisible(true);
            btnVolunteer.setVisible(true);
            btnHelp.setVisible(true);
        } else if (comp instanceof DoneeWorkAreaJPanel) {
            btnHelp.setVisible(true);
        } else if (comp instanceof DonorWorkAreaJPanel) {
            btnDonate.setVisible(true);
        } else if (comp instanceof VolunteerWorkAreaJPanel) {
            btnVolunteer.setVisible(true);
        }

    }

    private void defaultView() {
        txtName.setEnabled(false);
        txtContact.setEnabled(false);
        txtEmail.setEnabled(false);
        txtService.setEnabled(false);
        txtAddr.setEnabled(false);
        txtDes.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnSave.setEnabled(false);
    }

    private void updateView() {
        txtName.setEnabled(true);
        txtContact.setEnabled(true);
        txtDes.setEnabled(true);
        txtEmail.setEnabled(true);
        txtService.setEnabled(true);
        txtAddr.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }

    public void displayFoodBank() {
        txtName.setText(foodbank.getName());
        txtContact.setText(foodbank.getPhone());
        txtEmail.setText(foodbank.getEmail());
        txtAddr.setText(foodbank.getAddress());
        txtDes.setText(foodbank.getAbout());
        txtService.setText(foodbank.getServiceDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVolunteer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnDonate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtService = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDes = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddr = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Food Bank Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 51, -1, -1));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 112, -1, -1));

        jLabel3.setText("Email；");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 189, -1, -1));

        jLabel4.setText("Address:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 228, -1, -1));

        btnVolunteer.setText("Volunteer");
        btnVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolunteerActionPerformed(evt);
            }
        });
        add(btnVolunteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, -1));

        jLabel5.setText("Sevice Provide:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 30));

        btnDonate.setText("Donate");
        btnDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateActionPerformed(evt);
            }
        });
        add(btnDonate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));

        jLabel6.setText("About this food bank:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 161, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 109, 161, -1));

        txtService.setColumns(20);
        txtService.setRows(5);
        jScrollPane1.setViewportView(txtService);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 360, 100));

        txtDes.setColumns(20);
        txtDes.setRows(5);
        jScrollPane2.setViewportView(txtDes);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 360, 90));

        jLabel7.setText("Contact: ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 144, -1, -1));
        add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 141, 161, -1));

        txtAddr.setColumns(20);
        txtAddr.setRows(5);
        jScrollPane3.setViewportView(txtAddr);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 228, 370, 56));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 519, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, -1));

        btnHelp.setText("Need Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolunteerActionPerformed
        VolunteerOpportunityJPanel volunteerOpportunityJPanel = new VolunteerOpportunityJPanel(userProcessContainer, customerAccount, foodbank);
        userProcessContainer.add("volunteerOpportunityJPanel", volunteerOpportunityJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnVolunteerActionPerformed

    private void btnDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateActionPerformed

        DonateJPanel donateJPanel = new DonateJPanel(userProcessContainer, customerAccount, foodbank);
        userProcessContainer.add("DonateJPanel", donateJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDonateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String foodBankName = txtName.getText();
        String contact = txtContact.getText();
        String address = txtAddr.getText();
        String email = txtEmail.getText();
        String about = txtDes.getText();
        String service = txtService.getText();
        if (!isValidName(foodBankName)) {
            JOptionPane.showMessageDialog(null, "Error: you have to fill in valid name!");
            return;
        }
        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(null, "Error: you have to fill in valid Email address!");
            return;
        }
        if (!isValidPhone(contact)) {
            JOptionPane.showMessageDialog(null, "Error: you have to fill in valid phone number!");
            return;
        }
        foodbank.setAddress(address);
        foodbank.setEmail(email);
        foodbank.setName(foodBankName);
        foodbank.setPhone(contact);
        foodbank.setServiceDescription(service);
        foodbank.setAbout(about);
        defaultView();
        JOptionPane.showMessageDialog(null, "Save the information successfully!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("GetSpecialHelp", new DoneeGetHelpJPanel(userProcessContainer, customerAccount, foodbank));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateView();
    }//GEN-LAST:event_btnUpdateActionPerformed

    public static boolean isValidPhone(String str) {
        if (str == null) {
            return false;
        }
        return str.matches("\\d{3}[-\\s]?\\d{3}[-\\s]?\\d{4}");
    }

    public static boolean isValidEmail(String str) {
        if (str == null) {
            return false;
        }
        return str.matches("[\\w.%+-]+@[\\w.-]+\\.[A-Za-z]{2,}");
    }

    public static boolean isValidUserName(String str) {
        if (str == null) {
            return false;
        }
        return str.matches("\\w+");
    }

    public static boolean isValidPassword(String str) {
        if (str == null) {
            return false;
        }
        return str.matches("\\w+");
    }

    public static boolean isValidName(String str) {
        if (str == null) {
            return false;
        }
        return str.matches("[a-zA-Z]+");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDonate;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnVolunteer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtAddr;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextArea txtDes;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtService;
    // End of variables declaration//GEN-END:variables
}
