/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerServiceRole;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.FoodBankEnterprise;
import business.Enterprise.FoodSupplierEnterprise;
import business.Organization.VolunteerServiceOrganization;
import business.UserAccount.EmployeeAccount;
import business.VolunteerJob.VolunteerJob;
import java.awt.CardLayout;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 梦菲
 */
public class ManageVolunteerJobListJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EmployeeAccount employeeAccount;
    private VolunteerServiceOrganization organization;
    private FoodBankEnterprise enterprise;
    private EcoSystem system;
    private boolean isAdd;

    /**
     * Creates new form ManageVolunteerJobListJPanel
     */
    ManageVolunteerJobListJPanel(JPanel userProcessContainer, EmployeeAccount employeeAccount, VolunteerServiceOrganization organization, FoodBankEnterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.employeeAccount = employeeAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.userProcessContainer.addContainerListener(new ContainerListener() {
            @Override
            public void componentAdded(ContainerEvent e) {

            }

            @Override
            public void componentRemoved(ContainerEvent e) {
                populateTable((FoodBankEnterprise) enterprise);
            }
        });
        populateTable(enterprise);
    }

    private void populateTable(FoodBankEnterprise enterprise) {
        DefaultTableModel model = (DefaultTableModel) tblVolunteerJobList.getModel();

        model.setRowCount(0);

        for (VolunteerJob volunteerJob : enterprise.getVolunteerJobs().getVolunteerJobList()) {
            Object[] row = new Object[2];
            row[0] = volunteerJob.getJobID();
            row[1] = volunteerJob;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVolunteerJobList = new javax.swing.JTable();
        btnViewDtails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Volunteer Job List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        tblVolunteerJobList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job ID", "Job Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVolunteerJobList);
        if (tblVolunteerJobList.getColumnModel().getColumnCount() > 0) {
            tblVolunteerJobList.getColumnModel().getColumn(0).setResizable(false);
            tblVolunteerJobList.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 108, 490, 190));

        btnViewDtails.setText("View Details");
        btnViewDtails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDtailsActionPerformed(evt);
            }
        });
        add(btnViewDtails, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDtailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDtailsActionPerformed
        int row = tblVolunteerJobList.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Pls select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        VolunteerJob volunteerJob = (VolunteerJob) tblVolunteerJobList.getValueAt(row, 1);

        ManageVolunteerJobJPanel manageVolunteerJobJPanel = new ManageVolunteerJobJPanel(userProcessContainer, employeeAccount, organization, enterprise, system, volunteerJob);
        userProcessContainer.add("manageVolunteerJobJPanel", manageVolunteerJobJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDtailsActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        ManageVolunteerJobJPanel manageVolunteerJobJPanel = new ManageVolunteerJobJPanel(userProcessContainer, employeeAccount, organization, enterprise, system, null);
        userProcessContainer.add("manageVolunteerJobJPanel", manageVolunteerJobJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblVolunteerJobList.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                VolunteerJob vj = (VolunteerJob) tblVolunteerJobList.getValueAt(selectedRow, 1);
                enterprise.getVolunteerJobs().deleteVolunteerJob(vj);
                JOptionPane.showMessageDialog(this, "The volunteer job has been deleted.", "Info", JOptionPane.INFORMATION_MESSAGE);
                populateTable(enterprise);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row from table", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewDtails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVolunteerJobList;
    // End of variables declaration//GEN-END:variables
}
