/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerServiceRole;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.FoodBankEnterprise;
import business.Organization.VolunteerServiceOrganization;
import business.UserAccount.EmployeeAccount;
import business.VolunteerJob.VolunteerJob;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 梦菲
 */
public class ManageVolunteerJobJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EmployeeAccount employeeAccount;
    private VolunteerServiceOrganization organization;
    private FoodBankEnterprise enterprise;
    private EcoSystem system;
    private VolunteerJob volunteerJob;

    /**
     * Creates new form PostVolunteerJobJPanel
     */
    public ManageVolunteerJobJPanel(JPanel userProcessContainer, EmployeeAccount employeeAccount, VolunteerServiceOrganization organization,
            FoodBankEnterprise enterprise, EcoSystem system, VolunteerJob volunteerJob) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.employeeAccount = employeeAccount;
        this.volunteerJob = volunteerJob;
        panelView();
    }

    public void panelView() {
        if (volunteerJob == null) {
            volunteerJob = new VolunteerJob();
            btnPost.setEnabled(true);
            btnUpdate.setEnabled(false);
            txtJobTitle.setEnabled(true);
            txtAreaJobDescription.setEnabled(true);
            txtRequirement.setEnabled(true);
            displayVolunteerJob();
        } else {
            btnPost.setEnabled(false);
            btnUpdate.setEnabled(true);
            txtJobTitle.setEnabled(false);
            txtAreaJobDescription.setEnabled(false);
            txtRequirement.setEnabled(false);
            displayVolunteerJob();
        }
    }

    public void displayVolunteerJob() {
        lblJobID.setText(String.valueOf(volunteerJob.getJobID()));
        txtJobTitle.setText(volunteerJob.getJobTitle());
        txtAreaJobDescription.setText(volunteerJob.getDescription());
        txtRequirement.setText(volunteerJob.getRequirement());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtJobTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRequirement = new javax.swing.JTextArea();
        btnPost = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaJobDescription = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblJobID = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Job title:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel2.setText("Volunteer Service - Manage Volunteer Job");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));
        add(txtJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 180, -1));

        jLabel3.setText("Job description:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel4.setText("Other requirement:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        txtRequirement.setColumns(20);
        txtRequirement.setRows(5);
        jScrollPane1.setViewportView(txtRequirement);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 343, 130));

        btnPost.setText("Post");
        btnPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostActionPerformed(evt);
            }
        });
        add(btnPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));

        txtAreaJobDescription.setColumns(20);
        txtAreaJobDescription.setRows(5);
        jScrollPane2.setViewportView(txtAreaJobDescription);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 332, 110));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        jLabel5.setText("Job ID:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        lblJobID.setText("<Show ID here>");
        add(lblJobID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostActionPerformed
        txtJobTitle.setEnabled(false);
        txtAreaJobDescription.setEnabled(false);
        txtRequirement.setEnabled(false);
        btnPost.setEnabled(false);
        btnUpdate.setEnabled(true);
        String jobTitle = txtJobTitle.getText();
        String description = txtAreaJobDescription.getText();
        String requirement = txtRequirement.getText();

        volunteerJob.setJobTitle(jobTitle);
        volunteerJob.setDescription(description);
        volunteerJob.setRequirement(requirement);
        volunteerJob.setInsitution(enterprise.getName());
        if (!enterprise.getVolunteerJobs().getVolunteerJobList().contains(volunteerJob)) {
            enterprise.getVolunteerJobs().getVolunteerJobList().add(volunteerJob);
        }
        JOptionPane.showMessageDialog(null, "Post volunteer job successfully!");

    }//GEN-LAST:event_btnPostActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        txtJobTitle.setEnabled(true);
        txtAreaJobDescription.setEnabled(true);
        txtRequirement.setEnabled(true);
        btnPost.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPost;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblJobID;
    private javax.swing.JTextArea txtAreaJobDescription;
    private javax.swing.JTextField txtJobTitle;
    private javax.swing.JTextArea txtRequirement;
    // End of variables declaration//GEN-END:variables
}
