/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerServiceRole;

import business.EcoSystem;
import business.UserAccount.*;
import business.Organization.Organization;
import business.Enterprise.Enterprise;
import business.Enterprise.FoodBankEnterprise;
import business.Organization.VolunteerServiceOrganization;
import business.VolunteerJob.VolunteerJob;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.Enterprise.FindFoodBankJPanel;

/**
 *
 * @author 梦菲
 */
public class VolunteerServiceWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EmployeeAccount employeeAccount;
    private VolunteerServiceOrganization organization;
    private FoodBankEnterprise enterprise;
    private EcoSystem system;
    /**
     * Creates new form VolunteerServiceWorkAreaJPanel
     */
    public VolunteerServiceWorkAreaJPanel(JPanel userProcessContainer, EmployeeAccount employeeAccount, 
                VolunteerServiceOrganization inOrganization, FoodBankEnterprise inEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.employeeAccount = employeeAccount;
        this.organization = inOrganization;
        this.enterprise = inEnterprise;
        this.system = EcoSystem.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageJobs = new javax.swing.JButton();
        btnAcceptVolunteer = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Volunteer Service Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        btnManageJobs.setText("Manage Volunteer Jobs");
        btnManageJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageJobsActionPerformed(evt);
            }
        });
        add(btnManageJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        btnAcceptVolunteer.setText("Accept Volunteer");
        btnAcceptVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptVolunteerActionPerformed(evt);
            }
        });
        add(btnAcceptVolunteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageJobsActionPerformed
            ManageVolunteerJobListJPanel manageVolunteerJobListJPanel = new ManageVolunteerJobListJPanel(userProcessContainer,employeeAccount, organization,enterprise, system);
            userProcessContainer.add("manageVolunteerJobListJPanel", manageVolunteerJobListJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageJobsActionPerformed

    private void btnAcceptVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptVolunteerActionPerformed
            AcceptVolunteerJPanel acceptVolunteerJPanel = new AcceptVolunteerJPanel(userProcessContainer,enterprise,employeeAccount);
            userProcessContainer.add("acceptVolunteerJPanel", acceptVolunteerJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAcceptVolunteerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptVolunteer;
    private javax.swing.JButton btnManageJobs;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
