/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManageFoodRole;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.FoodBankEnterprise;
import business.Enterprise.FoodSupplierEnterprise;
import business.Food.Food;
import business.Organization.ManageFoodOrganization;
import business.UserAccount.EmployeeAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author 梦菲
 */
public class ManageFoodWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EmployeeAccount employeeAccount;
    private ManageFoodOrganization organization;
    private Enterprise enterprise;
    private EcoSystem system;

    /**
     * Creates new form ManageFoodWorkAreaJPanel
     */
    public ManageFoodWorkAreaJPanel(JPanel userProcessContainer, EmployeeAccount employeeAccount,
            ManageFoodOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.employeeAccount = employeeAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageFood = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Manage Food Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 46, -1, -1));

        btnManageFood.setText("Manage Food Storage>>");
        btnManageFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFoodActionPerformed(evt);
            }
        });
        add(btnManageFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 197, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFoodActionPerformed
        if (enterprise instanceof FoodBankEnterprise) {
            FoodBankManageFoodJPanel foodBankManageFoodJPanel = new FoodBankManageFoodJPanel(userProcessContainer, employeeAccount, organization, enterprise, system);
            userProcessContainer.add("foodBankManageFoodJPanel", foodBankManageFoodJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else if (enterprise instanceof FoodSupplierEnterprise) {
            FoodSupplierManageFoodJPanel foodSupplierManageFoodJPanel = new FoodSupplierManageFoodJPanel(userProcessContainer, employeeAccount, organization, enterprise, system);
            userProcessContainer.add("foodSupplierManageFoodJPanel", foodSupplierManageFoodJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }

    }//GEN-LAST:event_btnManageFoodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageFood;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
