/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Customer;

import business.User.Customer;
import business.UserAccount.CustomerAccount;
import business.WorkQueue.GetHelpRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.VolunteerServiceRole.AcceptVolunteerJPanel;

/**
 *
 * @author 梦菲
 */
public class CustomerProfileJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private CustomerAccount customerAccount;
    private Customer customer;

    public CustomerProfileJPanel(JPanel userProcessContainer, CustomerAccount customerAccount) {
       initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerAccount = customerAccount;
        customer = customerAccount.getCustomer();
        displayCustomer();
        defaultView();
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        if (component instanceof AcceptVolunteerJPanel){
        btnUpdateProfile.setVisible(false);
        saveProfile.setVisible(false);
    }
        else{
        btnUpdateProfile.setVisible(true);
        saveProfile.setVisible(true); 
        }
    }

    private void displayCustomer(){
        txtFirstName.setText(customer.getFirstName());
        txtLastName.setText(customer.getLastName());
        txtPhone.setText(customer.getPhone());
        txtAddr.setText(customer.getAddress());
        txtEmail.setText(customer.getEmailAddress());
        txtSelfIntro.setText(customer.getSelfIntroduce());
        
    }
    private void defaultView(){
        txtFirstName.setEditable(false);
        txtLastName.setEditable(false);
        txtPhone.setEditable(false);
        txtEmail.setEditable(false);
        txtSelfIntro.setEditable(false);
        txtAddr.setEditable(false);
        btnUpdateProfile.setEnabled(true);
        saveProfile.setEnabled(false);
    }
    
    private void updateView(){
        txtFirstName.setEditable(true);
        txtLastName.setEditable(true);
        txtPhone.setEditable(true);
        txtEmail.setEditable(true);
        txtSelfIntro.setEditable(true);
        txtAddr.setEditable(true); 
        saveProfile.setEnabled(true);
        btnUpdateProfile.setEnabled(false);
    }

     public static boolean isValidPhone(String str){
        if (str == null)
            return false;
        return str.matches("\\d{3}[-\\s]?\\d{3}[-\\s]?\\d{4}");     
    }
     public static boolean isValidEmail(String str){
        if (str == null)
            return false;
        return str.matches("[\\w.%+-]+@[\\w.-]+\\.[A-Za-z]{2,}");     
    }
         public static boolean isValidName(String str){
        if(str == null){
            return false;
        }
        return str.matches("[a-zA-Z]+");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btnUpdateProfile = new javax.swing.JButton();
        saveProfile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSelfIntro = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddr = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Customer Work Area-personal profile");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 350, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 146, -1));

        btnUpdateProfile.setText("Update");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });
        add(btnUpdateProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, -1));

        saveProfile.setText("Save");
        saveProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProfileActionPerformed(evt);
            }
        });
        add(saveProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 87, -1));

        jLabel3.setText("Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel4.setText("Email Address:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel5.setText("Phone:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel7.setText("Self Introduce (For who want to become a volunteer or need special help):");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        txtSelfIntro.setColumns(20);
        txtSelfIntro.setRows(5);
        jScrollPane1.setViewportView(txtSelfIntro);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 572, 79));

        jLabel9.setText("First Name:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 117, -1));

        txtAddr.setColumns(20);
        txtAddr.setRows(5);
        jScrollPane2.setViewportView(txtAddr);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 350, 48));

        jLabel10.setText("Last Name:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 117, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void saveProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProfileActionPerformed
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String address = txtAddr.getText();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        String selfIntroduce = txtSelfIntro.getText();
         if(!isValidName(firstName) || !isValidName(lastName)){
            JOptionPane.showMessageDialog(null,"Error: you have to fill in valid name!");
            return;
        }
        if(!isValidEmail(email)){
                        JOptionPane.showMessageDialog(null,"Error: you have to fill in valid Email address!");
            return;
        }
        if(!isValidPhone(phone)){
             JOptionPane.showMessageDialog(null,"Error: you have to fill in valid phone number!");
             return;
        }
        customer.setAddress(address);
        customer.setEmailAddress(email);
        customer.setFirstName(firstName);
        customer.setLastName(lastName);
        customer.setPhone(phone);
        customer.setSelfIntroduce(selfIntroduce);
        defaultView();

    }//GEN-LAST:event_saveProfileActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
       updateView();
    }//GEN-LAST:event_btnUpdateProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton saveProfile;
    private javax.swing.JTextArea txtAddr;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextArea txtSelfIntro;
    // End of variables declaration//GEN-END:variables
}
