/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Customer;

import business.EcoSystem;
import business.UserAccount.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.Donee.DoneeWorkAreaJPanel;
import userinterface.Donee.FindFoodJPanel;
import userinterface.Donor.DonorWorkAreaJPanel;
import userinterface.Enterprise.FindFoodBankJPanel;
import userinterface.Volunteer.VolunteerWorkAreaJPanel;

/**
 *
 * @author 梦菲
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    private CustomerAccount customerAccount;
    private EcoSystem system;
    private JPanel userProcessContainer;

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public CustomerWorkAreaJPanel(EcoSystem system, CustomerAccount customerAccount, JPanel container) {
        initComponents();
        this.system = system;
        this.customerAccount = customerAccount;
        this.userProcessContainer = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FindFoodBank = new javax.swing.JButton();
        btnVolunteer = new javax.swing.JButton();
        btnDonate = new javax.swing.JButton();
        btnModifyProfile = new javax.swing.JButton();
        btnGetHelp = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Customer Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        FindFoodBank.setText("Find Food Bank");
        FindFoodBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindFoodBankActionPerformed(evt);
            }
        });
        add(FindFoodBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        btnVolunteer.setText("Volunteer");
        btnVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolunteerActionPerformed(evt);
            }
        });
        add(btnVolunteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        btnDonate.setText("Donate");
        btnDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateActionPerformed(evt);
            }
        });
        add(btnDonate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        btnModifyProfile.setText("Modify Profile");
        btnModifyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyProfileActionPerformed(evt);
            }
        });
        add(btnModifyProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        btnGetHelp.setText("Get Help");
        btnGetHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetHelpActionPerformed(evt);
            }
        });
        add(btnGetHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void FindFoodBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindFoodBankActionPerformed
        FindFoodBankJPanel findFoodBankJPanel = new FindFoodBankJPanel(userProcessContainer, customerAccount);
        userProcessContainer.add("findFoodBankJPanel", findFoodBankJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_FindFoodBankActionPerformed

    private void btnVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolunteerActionPerformed
        VolunteerWorkAreaJPanel volunteerWorkAreaJPanel = new VolunteerWorkAreaJPanel(userProcessContainer, customerAccount);
        userProcessContainer.add("volunteerWorkAreaJPanel", volunteerWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnVolunteerActionPerformed

    private void btnDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateActionPerformed
        DonorWorkAreaJPanel donorWorkAreaJPanel = new DonorWorkAreaJPanel(userProcessContainer, customerAccount);
        userProcessContainer.add("donorWorkAreaJPanel", donorWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDonateActionPerformed

    private void btnModifyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyProfileActionPerformed
        CustomerProfileJPanel customerProfileJPanel = new CustomerProfileJPanel(userProcessContainer, customerAccount);
        userProcessContainer.add("customerProfileJPanel", customerProfileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnModifyProfileActionPerformed

    private void btnGetHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetHelpActionPerformed
        DoneeWorkAreaJPanel doneeWorkAreaJPanel = new DoneeWorkAreaJPanel(userProcessContainer, customerAccount);
        userProcessContainer.add("DoneeWorkAreaJPanel", doneeWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnGetHelpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FindFoodBank;
    private javax.swing.JButton btnDonate;
    private javax.swing.JButton btnGetHelp;
    private javax.swing.JButton btnModifyProfile;
    private javax.swing.JButton btnVolunteer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
