/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Customer;

import business.UserAccount.*;
import business.EcoSystem;
import business.User.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 梦菲
 */
public class CustomerRegisterJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;

    public CustomerRegisterJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        txtUserName.setText("");
        txtPassword.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmailAddress.setText("");
    }

    public static boolean isValidPhone(String str) {
        if (str == null) {
            return false;
        }
        return str.matches("\\d{3}[-\\s]?\\d{3}[-\\s]?\\d{4}");
    }

    public static boolean isValidEmail(String str) {
        if (str == null) {
            return false;
        }
        return str.matches("[\\w.%+-]+@[\\w.-]+\\.[A-Za-z]{2,}");
    }

    public static boolean isValidUserName(String str) {
        if (str == null) {
            return false;
        }
        return str.matches("\\w+");
    }

    public static boolean isValidPassword(String str) {
        if (str == null) {
            return false;
        }
        return str.matches("\\w+");
    }

    public static boolean isValidName(String str) {
        if (str == null) {
            return false;
        }
        return str.matches("[a-zA-Z]+");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        txtEmailAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel2.setText("Password:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 156, -1, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 153, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 153, -1));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));
        add(txtEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 153, -1));

        jLabel3.setText("Email Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel4.setText("Customer Register");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 25, -1, -1));

        jLabel5.setText("First Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 149, -1));

        jLabel8.setText("Last Name:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 149, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        CustomerAccount ca = new CustomerAccount();

        String username = txtUserName.getText();
        String password = txtPassword.getText();
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String email = txtEmailAddress.getText();
        if (!isValidUserName(username)) {
            JOptionPane.showMessageDialog(null, "Error: you have to fill in a valid User Name!");
            return;
        }
        if (!isValidPassword(password)) {
            JOptionPane.showMessageDialog(null, "Error: you have to fill in a valid password!");
            return;
        }
        if (!isValidName(firstName) || !isValidName(lastName)) {
            JOptionPane.showMessageDialog(null, "Error: you have to fill in valid name!");
            return;
        }
        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(null, "Error: you have to fill in valid Email address!");
            return;
        }
        Customer customer = new Customer();
        customer.setFirstName(firstName);
        customer.setLastName(lastName);
        customer.setEmailAddress(email);
        if (!system.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
            JOptionPane.showMessageDialog(null, "The User Name has bean registered, please try another one.");
        } else {
            system.getUserAccountDirectory().createCustomerAccount(username, password, customer);
            JOptionPane.showMessageDialog(null, "Successfully! Please try login");
            txtUserName.setText("");
            txtPassword.setText("");
            txtFirstName.setText("");
            txtLastName.setText("");
            txtEmailAddress.setText("");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
