/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Donee;

import business.UserAccount.*;
import business.Enterprise.Enterprise;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import userinterface.Enterprise.FindFoodBankJPanel;

/**
 *
 * @author asahoho
 */
public class DoneeWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CustomerAccount customerAccount;
    private Enterprise enterprise;

    /**
     * Creates new form DoneeWorkAreaJPanel
     */
    public DoneeWorkAreaJPanel(JPanel userProcessContainer, CustomerAccount customerAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerAccount = customerAccount;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFindFoodBank = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCheckFeedBack = new javax.swing.JButton();
        btnFindFood = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Donee Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        btnFindFoodBank.setText("Find your local food bank>>");
        btnFindFoodBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindFoodBankActionPerformed(evt);
            }
        });
        add(btnFindFoodBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        btnCheckFeedBack.setText("Check feedback ");
        btnCheckFeedBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckFeedBackActionPerformed(evt);
            }
        });
        add(btnCheckFeedBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        btnFindFood.setText("Find food>>");
        btnFindFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindFoodActionPerformed(evt);
            }
        });
        add(btnFindFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindFoodBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindFoodBankActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("FindFoodBank", new FindFoodBankJPanel(userProcessContainer, customerAccount));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFindFoodBankActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCheckFeedBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckFeedBackActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("CheckFeedback", new RequestStatusJPanel(userProcessContainer, customerAccount));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCheckFeedBackActionPerformed

    private void btnFindFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindFoodActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("findFoodJPanel", new FindFoodJPanel(userProcessContainer, customerAccount));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFindFoodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckFeedBack;
    private javax.swing.JButton btnFindFood;
    private javax.swing.JButton btnFindFoodBank;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
