/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Donee;

import business.User.*;
import business.UserAccount.*;
import business.Enterprise.Enterprise;
import business.Enterprise.FoodBankEnterprise;
import business.Organization.AdminOrganization;
import business.Organization.Organization;
import business.WorkQueue.GetHelpRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 梦菲
 */
public class DoneeGetHelpJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CustomerAccount customerAccount;
    private FoodBankEnterprise enterprise;

    /**
     * Creates new form GetHelpJPanel
     */

    public DoneeGetHelpJPanel(JPanel userProcessContainer, CustomerAccount customerAccount, FoodBankEnterprise foodbank) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerAccount = customerAccount;
        this.enterprise = foodbank;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaRequirement = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Get Special Help");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        txtAreaRequirement.setColumns(20);
        txtAreaRequirement.setRows(5);
        jScrollPane2.setViewportView(txtAreaRequirement);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 474, 220));

        jLabel4.setText("Write down the help you want to get, or any story you want to share.");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        jLabel2.setText("We will try to help you better.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String message = txtAreaRequirement.getText();
        GetHelpRequest request = new GetHelpRequest();
        request.setMessage(message);
        request.setSender(customerAccount);
        request.setStatus("Sent");
        customerAccount.getWorkQueue().getWorkRequestList().add(request);
        enterprise.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "We've received your request. Please check your feedback in 3 business days.");
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAreaRequirement;
    // End of variables declaration//GEN-END:variables
}
